### PR TITLE
Fix added timestamp truncated

### LINKED ISSUE #15: Don't work
Hey i added conf in following way but i still don't have value in milliseconds.

```
<filter **>
  type elasticsearch_timestamp_check
  subsecond_precision 3
</filter>
```

@timestamp |   | October 1st 2020, 11:48:23.000
fluent_added_timestamp |   | October 1st 2020, 11:48:23.000

### LINKED ISSUE #17: Fluent added timestamp truncated to seconds
In the case `@timestamp`  (and `fluent_added_timestamp`) is added from fluentd event time, the timestamp is truncated to seconds.

The cause is the conversion of the time to an integer ([Fluent::EventTime - to_int](https://www.rubydoc.info/gems/fluentd/Fluent/EventTime#to_int-instance_method))

https://github.com/ecwws/fluent-plugin-elasticsearch-timestamp-check/blob/98862cfeb6435002cc4ece2cef47e07acfcc85e2/lib/fluent/plugin/filter_elasticsearch_timestamp_check.rb#L68

(It is the same issue as https://github.com/ecwws/fluent-plugin-elasticsearch-timestamp-check/issues/15 but it was not described good enough)

## Proposed solution
Use `to_r` method instead ([Fluent::EventTime - to_r](https://www.rubydoc.info/gems/fluentd/Fluent/EventTime#to_r-instance_method) which converts it in a Time object ready to use with `Time.at`

### PR DESCRIPTION
**Pull request by tsotnikov**
Closes https://github.com/ecwws/fluent-plugin-elasticsearch-timestamp-check/issues/15 and closes https://github.com/ecwws/fluent-plugin-elasticsearch-timestamp-check/issues/17

### CODE REVIEW

**Comment by tsotnikov** [comment]
Tested locally in my setup that the fix works.

Long time since the last commit in this repository, if it still maintained please review @ecwws

**Comment by ecwws** [comment]
thanks for fixing this, haven't had time lately, i'll get this one merged and published

**Comment by tsotnikov** [comment]
Great! Thank you very much for the quick response!

**Comment by ecwws** [comment]
gem version 0.3.1 is published

**Comment by tsotnikov** [comment]
Tested that 0.3.1 works correctly :+1:

**Pull request merged**
